queue:
  name: VSEng-MicroBuildVS2017
  condition: succeeded()
  demands: msbuild


#Your build definition references the ‘SignType’ variable, which you’ve selected to be settable at queue time. Create or edit the build definition for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build definition references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build definition for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build definition references the ‘SignType’ variable, which you’ve selected to be settable at queue time. Create or edit the build definition for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build definition references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build definition for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build definition references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build definition for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build definition references the ‘SignType’ variable, which you’ve selected to be settable at queue time. Create or edit the build definition for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build definition references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build definition for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build definition references the ‘BuildConfiguration’ variable, which you’ve selected to be settable at queue time. Create or edit the build definition for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
#Your build definition references an undefined variable named ‘NugetPackagesPath’. Create or edit the build definition for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
variables:
  BuildPlatform: ''
steps:
- task: ms-vseng.MicroBuildTasks.30666190-6959-11e5-9f96-f56098202fef.MicroBuildSigningPlugin@1
  displayName: Install Signing Plugin
  inputs:
    signType: '$(SignType)'

- task: DotNetCoreInstaller@0
  displayName: Use .NET Core sdk 2.0.0
  inputs:
    version: 2.0.0
  enabled: false

- task: DotNetCoreCLI@1
  displayName: dotnet pack
  inputs:
    command: pack
    projects: MSBuildLocator.sln
    arguments: '/p:Configuration=$(BuildConfiguration) /p:SignType=$(SignType)'
  enabled: false

- task: MSBuild@1
  displayName: /t:Restore
  inputs:
    solution: MSBuildLocator.sln
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '/t:Restore'
  enabled: false

- task: MSBuild@1
  displayName: /t:Build
  inputs:
    solution: MSBuildLocator.sln
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '/t:Build /p:SignType=$(SignType) /restore'
  enabled: false

- task: MSBuild@1
  displayName: /t:Pack
  inputs:
    solution: MSBuildLocator.sln
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '/t:Pack /restore'

- task: CopyFiles@2
  displayName: Collect Symbols
  inputs:
    SourceFolder: 'src/MSBuildLocator'
    Contents: '**\*.pdb'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/symbols'
    CleanTargetFolder: true

- task: PublishSymbols@1
  displayName: Index Sources
  inputs:
    SearchPattern: '**/*.pdb'
    SymbolsFolder: '$(Build.ArtifactStagingDirectory)\symbols'
  enabled: false

- task: PublishBuildArtifacts@1
  displayName: Upload Symbols Artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/symbols'
    ArtifactName: Symbols

- task: CopyPublishBuildArtifacts@1
  displayName: Upload Bin to drop
  inputs:
    Contents: |
     src\MSBuildLocator\bin\**
     
    ArtifactName: bin
    ArtifactType: Container

- task: CopyPublishBuildArtifacts@1
  displayName: Upload NuGet to drop
  inputs:
    Contents: |
     src\MSBuildLocator\bin\$(BuildConfiguration)\*.nupkg
     
    ArtifactName: pkg
    ArtifactType: Container

- task: ms-vscs-artifact.build-tasks.artifactSymbolTask-1.artifactSymbolTask@0
  displayName: Publish Symbols to Artifact Services
  inputs:
    symbolServiceURI: 'https://microsoft.artifacts.visualstudio.com/DefaultCollection'
    sourcePath: '$(Build.ArtifactStagingDirectory)\symbols'
    usePat: false
  enabled: false

- task: CopyPublishBuildArtifacts@1
  displayName: Upload MicroBuildOutputs to drop
  inputs:
    CopyRoot: '$(Build.StagingDirectory)\MicroBuild\Output'
    Contents: '**'
    ArtifactName: MicroBuildOutputs
    ArtifactType: Container
  continueOnError: true

- task: NuGetPublisher@0
  displayName: Publish Nuget packages to Myget
  inputs:
    searchPattern: '$(NugetPackagesPath)\**.nupkg'
    connectedServiceName: 'dotnet.myget.org msbuild'
  enabled: false

- task: CopyPublishBuildArtifacts@1
  displayName: Upload logs to drop
  inputs:
    Contents: '**\*.log'
    ArtifactName: logs
    ArtifactType: Container
  condition: succeededOrFailed()

- task: ms-vseng.MicroBuildTasks.521a94ea-9e68-468a-8167-6dcf361ea776.MicroBuildCleanup@1
  displayName: Execute cleanup tasks

